import Link from "next/link";

export default function Home() {
  return (
    <main>
      <header className="site-header"><div className="nav-wrap"><Link href="/" className="brand" style={{textDecoration:"none"}}><span className="brand-mark" />JOBHUNT<span>PRO</span></Link><nav className="nav-links"><a href="#features">Features</a><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="#blog">Blog</a></nav><div className="nav-actions"><Link href="/login" className="btn btn-ghost">Log in</Link><Link href="/signup" className="btn btn-primary">Sign up</Link></div></div></header>
      <section className="hero"><div className="hero-grid"><div><span className="eyebrow">● AI-POWERED JOB SEARCH</span><h1>Find the right jobs, <span>faster.</span></h1><p className="hero-copy">Connect your resume and job sources, let AI find relevant opportunities, understand your fit, and move from discovery to application with less friction.</p><div className="hero-actions"><Link href="/signup" className="btn btn-primary">Get started for free →</Link><a href="#how" className="btn btn-ghost">See how it works</a></div><div className="hero-proof"><span>AI job matching</span><span>Multi-platform search</span><span>Save & track applications</span></div></div><div className="hero-panel"><div className="panel-head"><span>Job matches</span><span style={{color:"#5a4fcf"}}>128 found</span></div><div className="search-box">⌕ Search jobs, companies or keywords...</div><div className="job-list"><div className="job-row"><div className="company-logo">G</div><div><h4>Salesforce Project Manager</h4><p>Google · Bengaluru · Full-time</p></div><span className="match">92% Match</span></div><div className="job-row"><div className="company-logo">M</div><div><h4>Technical Project Manager</h4><p>Microsoft · Hyderabad · Hybrid</p></div><span className="match">89% Match</span></div><div className="job-row"><div className="company-logo">A</div><div><h4>Product Manager — Digital</h4><p>Accenture · Gurugram · Full-time</p></div><span className="match">86% Match</span></div></div></div></div></section>
      <section className="section" id="features"><div className="section-inner"><div className="section-title"><h2>Everything you need to job hunt smarter.</h2><p>Less time searching. More time on the opportunities that actually fit.</p></div><div className="feature-grid"><article className="feature-card"><div className="feature-icon">⌕</div><h3>AI job matching</h3><p>Compare your experience, skills and preferences against each opportunity and surface relevant matches.</p></article><article className="feature-card"><div className="feature-icon">↗</div><h3>One job feed</h3><p>Bring opportunities from the job platforms you use into one focused discovery experience.</p></article><article className="feature-card"><div className="feature-icon">✓</div><h3>Track & apply</h3><p>Save jobs, track application progress and open the original job listing when you're ready to apply.</p></article></div></div></section>
      <section className="section" id="how" style={{background:"#fff"}}><div className="section-inner"><div className="section-title"><h2>From resume to relevant jobs.</h2><p>Connect your profile, discover matches, review your fit, and apply on the original platform.</p></div></div></section>
    </main>
  );
}