"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
export default function SignupPage(){
 const [form,setForm]=useState({name:"",email:"",phone:"",password:"",confirmPassword:""}); const [error,setError]=useState(""); const [done,setDone]=useState(false); const [loading,setLoading]=useState(false);
 const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
 async function submit(e:FormEvent){e.preventDefault();setError("");setLoading(true); const r=await fetch("/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}); const d=await r.json(); setLoading(false); if(!r.ok){setError(d.error||"Could not create account.");return} setDone(true);}
 if(done) return <main className="auth-shell"><section className="auth-card"><div className="brand">JobFit<span>Pro</span></div><div className="success-icon">✓</div><h1>Check your email</h1><p className="sub">We sent a verification link to <strong>{form.email}</strong>. Verify your email to continue to account setup.</p><Link className="primary link-button" href="/login">Go to login</Link></section></main>;
 return <main className="auth-shell"><section className="auth-card"><div className="brand">JobFit<span>Pro</span></div><h1>Create your account</h1><p className="sub">Start finding jobs that fit your profile.</p><form onSubmit={submit}><label>Full name<input value={form.name} onChange={e=>update("name",e.target.value)} placeholder="Your name" required /></label><label>Email<input type="email" value={form.email} onChange={e=>update("email",e.target.value)} placeholder="you@example.com" required /></label><label>Phone number<input type="tel" value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="+91 98765 43210" required /></label><label>Password<input type="password" value={form.password} onChange={e=>update("password",e.target.value)} placeholder="At least 8 characters" required minLength={8} /></label><label>Confirm password<input type="password" value={form.confirmPassword} onChange={e=>update("confirmPassword",e.target.value)} placeholder="Repeat your password" required /></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={loading}>{loading?"Creating account…":"Create account"}</button></form><p className="switch">Already have an account? <Link href="/login">Log in</Link></p></section></main>
}
